export const productsDB = [
  {
    id: 1,
    price: "10$",
    availableSizes: ["XS", "S", "L"],
    title: "cloth no.1",
    quantity: 1,
  },
  {
    id: 2,
    price: "40$",
    availableSizes: ["S", "XXL", "M"],
    title: "cloth no.2",
    quantity: 1,
  },
  {
    id: 3,
    price: "41$",
    availableSizes: ["XS", "S", "L"],
    title: "cloth no.3",
    quantity: 1,
  },
  {
    id: 4,
    price: "41$",
    availableSizes: ["XS", "S", "L", "XXL"],
    title: "cloth no.4",
    quantity: 1,
  },
  {
    id: 5,
    price: "9$",
    availableSizes: ["S"],
    title: "cloth no.5",
    quantity: 1,
  },
  {
    id: 6,
    price: "11$",
    availableSizes: ["XS", "S"],
    title: "cloth no.6",
    quantity: 1,
  },
  {
    id: 7,
    price: "13$",
    availableSizes: ["XS", "S", "L", "XL"],
    title: "cloth no.7",
    quantity: 1,
  },
  {
    id: 8,
    price: "14$",
    availableSizes: ["L"],
    title: "cloth no.8",
    quantity: 1,
  },
  {
    id: 9,
    price: "15$",
    availableSizes: ["XS", "L", "XXL"],
    title: "cloth no.9",
    quantity: 1,
  },
  {
    id: 10,
    price: "15$",
    availableSizes: ["XS"],
    title: "cloth no.10",
    quantity: 1,
  },
];
